### ISSUE TITLE
executable binaries or libs

### ISSUE THREAD

**Issue by jbellic** [robertwgh/ezSIFT#10]
Hi,

I'm interested in using ezSift within a Java application which will be deployed later on a windows + linux machine. Is there any executable or lib file that I can call from within java code?

Thanks in advance.

**Comment by robertwgh** [comment]
You can use JNI to call native functions from JAVA.
Please refer to JNI examples for Android, https://developer.android.com/ndk/samples/sample_hellojni. It is pretty straightforward.
