### ISSUE TITLE
a question:;the keypoint number extracted by ezsift is much less than opencv,.

### ISSUE THREAD

**Issue by tongjuntx** [robertwgh/ezSIFT#12]

**Comment by robertwgh** [comment]
there are quite a lot parameters to tune in SIFT algorithm, such as threshold and so on. Different implementation has different default values, so you can definitely tune those parameters to make it work as you expected. 

You can read the wiki part. Although OpenCV one provides more KPs, the quality might not be better. It is up to you to select the right parameter configurations.

**Comment by tongjuntx** [comment]
> there are quite a lot parameters to tune in SIFT algorithm, such as threshold and so on. Different implementation has different default values, so you can definitely tune those parameters to make it work as you expected.
> 
> You can read the wiki part. Although OpenCV one provides more KPs, the quality might not be better. It is up to you to select the right parameter configurations.

Thanks for your reply, I will carefully read your source code
